# My Tmux config file

# Notes - Hotkey definitions
## C Control
## M Meta/Alt

# Notes - How to use copy mode
## Ctrl + a then [ to enter copy mode
## Space to begin selection
## Enter to copy selection
## Ctrl + a then ] to paste in tmux
## Or paste outside with normal control + v

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse mode for scrolling
set -g mouse on

# Set history limit to 10k
set -g history-limit 100000

# Enable copy/paste
## Enable clipboard to use copy mode
set -g set-clipboard on

# # Use vim keybindings in copy mode
setw -g mode-keys vi

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter

# Set copy hotkeys and enable mouse selection copy, requires "wl-clipboard"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "wl-copy --foreground --trim-newline"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy --foreground --trim-newline"

# Split panes
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch panes without prefix keys
# -n means no prefix
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

# Set terminal status color
set -g default-terminal "tmux-256color"
set -g status-bg colour10
set -g status-fg black

# Set terminal pane color
set -g pane-border-style fg=white
set -g pane-active-border-style "bg=default fg=colour10"

# Enable Truecolor support
set -as terminal-features ",*:RGB"

# Reload tmux config w/ message
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
